---

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g gulp-cli

script: gulp build
