---

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

language: node_js
node_js:
  - "lts/*"
  - "node"
matrix:
  allow_failures:
    - node_js: "node"

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g gulp-cli

script: gulp build
